services:
  - type: web
    name: love-diary-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      flask db init || true
      flask db migrate -m "Initial migration"
      flask db upgrade
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app  # MUST include $PORT
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PORT
        value: 10000  # Required for Render
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:///instance/love.db
